include ../../Makedefs

SMARK_ROOT = ../..
PACKAGE_DIR = sandmark/gui

FREE_CLASSES = AboutDialog.class \
   DecompileDialog.class \
   ExtensionFileFilter.class GraphDisplayButton.class HelpDialog.class \
   SMarkGUIConstants.class SandMarkFrame.class SandMarkLiteFrame.class \
   SandMarkGUIConstants.class SkinPanel.class \
   SplashPanel.class StatTableModel.class \
   SMAlgHierTreePane.class SMAlgHierTreeNode.class VSplitPanel.class \
   WebBrowser.class CopyrightDialog.class SandMarkMenuBar.class \
   DynamicWatermarkPanel.class DynamicEmbedPanel.class \
   DynamicTracePanel.class DynamicRecognizePanel.class \
   StaticWatermarkPanel.class StaticEmbedPanel.class StaticRecognizePanel.class \
   DecompilePanel.class OptimisePanel.class ObfuscatePanel.class ConfigPropertyPanel.class AlgorithmPanel.class \
   NextWMButton.class RecognizeButton.class AlgorithmComboBox.class ObfDialog.class \
   MethodSliceGUI.class DynamicRecognizeButton.class CurrentApplicationTracker.class \
   HelpButton.class HomePanel.class LiteHomePanel.class \
   SandMarkPanel.class FilenameBox.class \
   MultiLineToolTipUI.class \
   QuickProtectPanel.class LogPane.class AppViewPanel.class ViewPanel.class \
   StaticBirthmarkPanel.class DynamicBirthmarkPanel.class

FREE_DIRS = \
	diff \

include ../../rules.inc

