include ../../Makedefs

PACKAGE_DIR = sandmark/watermark


FREE_DIRS = bogusexp bogusinitializer ct addmethfield mondenwmark bogusswitch constantstring \
   hattrick objectwm assignlv gtw util objectwm dm \
   arboit steganography execpath

FREE_CLASSES = DynamicWatermarker.class \
   GeneralWatermarker.class \
   StaticEmbed.class \
   StaticRecognize.class \
   StaticWatermarker.class \
   WatermarkingException.class \
   DynamicEmbedParameters.class \
   DynamicRecognizeParameters.class \
   DynamicTraceParameters.class \
   StaticEmbedParameters.class \
   StaticRecognizeParameters.class \

include ../../rules.inc
