include ../../../../Makedefs

SMARK_ROOT = ../../../..
PACKAGE_DIR = sandmark/util/graph/graphview

FREE_CLASSES = \
   CreateGraph.class \
   DummyNode.class \
   EdgeDisplayInfo.class \
   GraphLayout.class \
   GraphList.class \
   GraphPanel.class \
   GraphViewFrame.class \
   GraphZoomSlider.class \
   HierarchyTreeLayout.class \
   LayeredDrawingLayout.class \
   NodeDisplayInfo.class \
   SimpleGraphLayout.class \
   SpringEmbedderLayout.class \
   TreeLayout.class \
   MutableGraphPanel.class

include ../../../../rules.inc
