include ../../../Makedefs

SMARK_ROOT = ../../..
PACKAGE_DIR = sandmark/obfuscate/methodmadness

FREE_CLASSES =  PrimitivePromoter.class \
   SignatureBludgeoner.class \
   StaticSplit.class \
   MethodMerger.class \
   ParamReorder.class \
   #Method2RMadness.class

include ../../../rules.inc
