include ../../Makedefs

SMARK_ROOT = ../..
PACKAGE_DIR = sandmark/optimise

FREE_DIRS = \
   bloat \

FREE_CLASSES = Optimise.class \
   AllClassesOptimizer.class \
   AppOptimizer.class \
   ClassOptimizer.class \
   GeneralOptimizer.class \
   MethodOptimizer.class \
   Optimizer.class \
   OptimizationException.class \

include ../../rules.inc
