include ../../../../Makedefs

SMARK_ROOT = ../../../..
PACKAGE_DIR = sandmark/watermark/ct/recognize

FREE_CLASSES = Heap2Graph.class RecognizeData.class Recognizer.class

include ../../../../rules.inc

