#  Makefile for Sandmark java code


include ../Makedefs

SMARK_ROOT = ..
PACKAGE_DIR = sandmark

FREE_DIRS = \
   visualize \
   config \
   gui \
   diff \
   obfuscate \
   optimise \
   program \
   newstatistics \
   metric \
   util \
   view \
   decompile \
   watermark \
   analysis \
   smash \
   wizard \
   birthmark 

FREE_CLASSES = \
   Algorithm.class \
   AppAlgorithm.class \
   ClassAlgorithm.class \
   Console.class \
   Constants.class \
   MethodAlgorithm.class


include ../rules.inc
