include ../../Makedefs

PACKAGE_DIR = sandmark/analysis


FREE_DIRS = \
   classhierarchy stacksimulator slicingtools \
   controlflowgraph dependencygraph callgraph \
   defuse liveness interference initialized

FREE_CLASSES = 

include ../../rules.inc
