#  Makefile for sandmark.program

include ../../../Makedefs

SMARK_ROOT = ../../..
PACKAGE_DIR = sandmark/program/util

FREE_CLASSES = Reference.class Renamer.class AllMethods.class

include ../../../rules.inc
