include ../../Makedefs

SMARK_ROOT = ../..
PACKAGE_DIR = sandmark/diff

FREE_DIRS = \
	methoddiff \
	classdiff \

FREE_CLASSES = \
	Result.class \
	LCS.class \
	Coloring.class \
	Monitorable.class \
	InstructionWrapper.class \
	DiffOptions.class \
	DiffUtil.class \
	DiffAlgorithm.class \

include ../../rules.inc
