include ../../Makedefs

PACKAGE_DIR = sandmark/wizard

FREE_DIRS = modeling \
            decision \
            evaluation \
            executive \
	    quickprotect \

NONFREE_DIRS = 

FREE_CLASSES = \
   AlgorithmProvider.class \
   AppProvider.class \
   ChoiceRunListener.class \
   ChoiceRunner.class \
   DefaultAlgorithmProvider.class \
   ObjectProvider.class \
   StaticWatermarkProvider.class \
   Wizard.class \
   

include ../../rules.inc
