include ../../../Makedefs
 
SMARK_ROOT = ../../..
PACKAGE_DIR = sandmark/birthmark/wpp
 
FREE_CLASSES = \
   WPP.class \
   Annotate.class \
   TracePoint.class \
   Tracer.class \
   Annotator.class \
   guard.class \
   nonTerminal.class \
   rule.class \
   RunSequitur.class \
   symbol.class \
   terminal.class \
   DAGNode.class \
   DAGEdge.class \

include ../../../rules.inc
