include ../../Makedefs

SMARK_ROOT = ../..
PACKAGE_DIR = sandmark/metric

FREE_CLASSES = \
Metric.class \
MethodMetric.class \
HalsteadMethodEffortMeasure.class \
HalsteadMethodDifficultyMeasure.class \
HalsteadMethodLengthMeasure.class \
HalsteadMethodVocabMeasure.class \
HalsteadMethodVolumeMeasure.class \
HarrisonMethodMeasure.class \
McCabeMethodMeasure.class \
MunsonMethodMeasure.class \
HalsteadMethodMeasure.class \
HalsteadUtil.class \
NestingLevelComplexity.class \
ClassMetric.class \
CkClassCouplingMeasure.class \
CkClassInheritanceMeasure.class \
CkClassResponseMeasure.class \
CkClassSubclassMeasure.class \
ApplicationComparator.class \
ClassComparator.class \
MethodComparator.class \
MethodOpcodeComparator.class \
ClassOpcodeComparator.class \
HalsteadClassDifficultyMeasure.class \
HalsteadClassEffortMeasure.class \
HalsteadClassLengthMeasure.class \
HalsteadClassVocabMeasure.class \
HalsteadClassVolumeMeasure.class \
ApplicationMetric.class \
AppIdentifierLength.class \
CkAppInheritanceMeasure.class \
CkAppResponseMeasure.class \
CkAppSubclassMeasure.class \
CkAppCouplingMeasure.class \
HalsteadAppDifficultyMeasure.class \
HalsteadAppEffortMeasure.class \
HalsteadAppLengthMeasure.class \
HalsteadAppVocabMeasure.class \
HalsteadAppVolumeMeasure.class \
HarrisonAppMeasure.class \
HarrisonClassMeasure.class \
KafuraAppMeasure.class \
KafuraClassMeasure.class \
McCabeClassMeasure.class \
McCabeAppMeasure.class \
LocalIdentifierLength.class \
ClassIdentifierLength.class \
MunsonClassMeasure.class \
HalsteadClassMeasure.class \
HalsteadAppMeasure.class \
CkClassMeasure.class \
CkAppMeasure.class \
MunsonAppMeasure.class \
#StatsUtil.class \
#Analyzer.class \

include ../../rules.inc
