include ../../../Makedefs

SMARK_ROOT = ../../..
PACKAGE_DIR = sandmark/util/newexprtree

FREE_CLASSES = ExprTreeCFG.class \
	Expr.class ExceptionInfo.class BasicBlock.class \
	ArithmeticExpr.class ArrayDummyExpr.class ArrayLengthExpr.class \
	ArrayLoadExpr.class ArrayStoreExpr.class BinaryArithmeticExpr.class \
	BranchExpr.class ComparisonExpr.class ConstantExpr.class ConversionExpr.class \
	DummyExpr.class ExceptionDummyExpr.class GetFieldExpr.class GotoExpr.class \
 	IfExpr.class IncExpr.class InstanceofExpr.class InvokeExpr.class JsrExpr.class \
	LoadExpr.class MonitorExpr.class NegateArithmeticExpr.class NewArrayExpr.class \
	NewExpr.class NopExpr.class NullConstantExpr.class NullConstantExpr.class \
	NumericConstantExpr.class ObjectDummyExpr.class PrimitiveDummyExpr.class \
	PutFieldExpr.class RetExpr.class ReturnAddressDummyExpr.class ReturnExpr.class \
	StoreExpr.class StringConstantExpr.class SwitchExpr.class ThrowExpr.class ValueExpr.class 
	
include ../../../rules.inc