include ../../Makedefs
 
PACKAGE_DIR = sandmark/birthmark

FREE_DIRS = \
   fieldvalues \
   methodcalls \
   usedclasses \
   inheritstruct \
   windows \
   util \
   wpp 

NONFREE_DIRS = \

FREE_CLASSES = \
   Birthmark.class \
   BirthmarkException.class \
   DynamicBirthmark.class \
   StaticClassBirthmark.class \
   GeneralBirthmark.class \

include ../../rules.inc
