include ../../../../../Makedefs

SMARK_ROOT = ../../../../..
PACKAGE_DIR = sandmark/watermark/ct/encode/ir

FREE_CLASSES = AddEdge.class \
   Build.class \
   Construct.class \
   Create.class \
   CreateNode.class \
   CreateStorage.class \
   Debug.class \
   Destroy.class \
   Destruct.class \
   Field.class \
   FieldAccessor.class \
   Fixup.class \
   FollowLink.class \
   Formal.class \
   IR.class \
   Init.class \
   List.class \
   LoadNode.class \
   Method.class \
   NodeStorage.class \
   PrintGraph.class \
   ProtectRegion.class \
   SaveNode.class \
   StaticCall.class

include ../../../../../rules.inc
