include ../../../Makedefs

SMARK_ROOT = ../../..
PACKAGE_DIR = sandmark/diff/methoddiff

FREE_CLASSES = \
	BakerAlgorithm.class \
	ComparableBlock.class \
	DMDiffAlgorithm.class \
	MethodDiffAlgorithm.class \
	TrivialDiffAlgorithm.class \
	Tuple.class \
	TupleList.class \
	CFGTreeNode.class \
	CFGTree.class \
	CFGDiff.class \

include ../../../rules.inc
