include ../../../../../Makedefs

SMARK_ROOT = ../../../../..
PACKAGE_DIR = sandmark/watermark/ct/trace/callforest

FREE_CLASSES = \
   Forest.class \
   Build.class \
   Decorate.class \
   Path.class \
   PathGenerator.class \
   CallFrame.class \
   Edge.class \
   Node.class \
   Test.class 

include ../../../../../rules.inc
