include ../../Makedefs

PACKAGE_DIR = sandmark/obfuscate

FREE_DIRS = \
   ArrayObfuscation\
   modifyifelse \
   setfieldspublic \
   reorder \
   renameidentifiers \
   methodmadness \
   blockmarker \
   varsplitter \
   appendboguscode \
   boolsplitter \
   localvar \
   boguspredicates \
   addbogusfields \
   buggycode \
   scalarmerger \
   inliner \
   instructionordering \
   promotelocals \
   stringencoder \
   encryptclasses \
   branchinsertion \
   nameoverloading \
   nodesplitter \
   classsplitter \
   interleavemethods \
   dynamicinliner \
   irreducibility \
   paramalias \
   objectify \
   insertopaquepred \
   #exceptionbranches \
   #boolsplitter \

NONFREE_DIRS = 

FREE_CLASSES = \
   AllClassesObfuscator.class \
   AppObfuscator.class \
   ClassObfuscator.class \
   GeneralObfuscator.class \
   MethodObfuscator.class \
   Obfuscator.class \
   ObfuscationException.class \

include ../../rules.inc
