include ../../../Makedefs

SMARK_ROOT = ../../..
PACKAGE_DIR = sandmark/util/opaquepredicatelib

FREE_CLASSES = \
	OpaquePredicateGenerator.class \
   OpaqueManager.class \
   smNode.class \
   ThreadPredicateGenerator.class \
   IntComparePredicateGenerator.class \
   ObjectComparePredicateGenerator.class \
   StringOpPredicateGenerator.class \
   PredicateInfo.class \
   PredicateFactory.class \
   ExprTree.class \
   AlgebraicPredicateGenerator.class \
   DataStructurePredicateGenerator.class \


# default-target: all-specialized

include ../../../rules.inc
