include ../../../Makedefs

SMARK_ROOT = ../../..
PACKAGE_DIR = sandmark/watermark/assignlv

FREE_CLASSES = AssignLV.class ToBinary.class MethodCompare.java FromBinary.class ClassNameMethodBundle.class ToArray.class
 
include ../../../rules.inc
