include ../../Makedefs

PACKAGE_DIR = sandmark/util

FREE_DIRS = classloading exec graph javagen \
   exprtree \
   newexprtree \
   opaquepredicatelib \
   stealth \
   newgraph \
   primitivepromotion \
   outliner \
   splitint

FREE_CLASSES = ArrayIterator.class \
   ByteCodeLocation.class \
   CircularBuffer.class \
   Combinations.class \
   ConfigProperties.class \
   ConfigPropertyChangeListener.class \
   Dot.class \
   Enum2Iter.class \
   FieldID.class \
   IdentifierIterator.class \
   Inliner.class \
   InstructionTree.class \
   Log.class \
   Math.class \
   MethodID.class \
   Misc.class \
   MultiIter.class \
   Options.class \
   PriorityQueue.class \
   Random.class \
   SparseVector.class \
   StackFrame.class \
   StringInt.class \
   TempDir.class \
   WeakBuffer.class \
   MethodSignatureChanger.class \
   ParamReorder.class \
   SignatureBludgeoner.class \
   MethodMerger.class \
   StaticSplit.class \
   MethodReceiver.class \
   MethodCaller.class \
   Publicizer.class

include ../../rules.inc
