include ../../../Makedefs

SMARK_ROOT = ../../..
PACKAGE_DIR = sandmark/util/primitivepromotion

FREE_CLASSES = 	LocalPromoter.class \
		PromoterException.class \
		PromoterUtil.class \
		ParamPromoter.class \
		ReturnPromoter.class

include ../../../rules.inc
