include ../../../Makedefs

SMARK_ROOT = ../../..
PACKAGE_DIR = sandmark/analysis/slicingtools

FREE_CLASSES = ForwardMethodSlice.class AnalysisBlock.class \
               BackwardMethodSlice.class MethodSlice.class

include ../../../rules.inc
