include ../../../../Makedefs

PACKAGE_DIR = sandmark/wizard/modeling/dfa

FREE_CLASSES = \
   DFA.class \
   DFAEdge.class \
   DFAModel.class \
   DFANode.class \
   IntermediateDFA.class \
   PostprohibitDFA.class \
   PostreqDFA.class \
   PreprohibitDFA.class \
   PrereqDFA.class \
   WeightMap.class \
   WeightPrimer.class

include ../../../../rules.inc
