include ../../../Makedefs

SMARK_ROOT = ../../..
PACKAGE_DIR = sandmark/analysis/stacksimulator

FREE_CLASSES = StackData.class \
   StackSimulator.class \
   Context.class \
   PrimitiveData.class \
   UninitializedReferenceData.class \
   ReferenceData.class \
   ClearStackContext.class \
   EmptyContext.class \
   MergeContext.class \
   PopContext.class \
   PushContext.class \
   ReplaceStackContext.class \
   ReplaceVarContext.class \
   UndefinedContext.class \
	CaughtExceptionData.class

include ../../../rules.inc
